#!/usr/bin/env bash
# bash completion for `flow` — generated by hand, not codegen. Sourced by the
# `# managed by flow completions` block written into ~/.bashrc / ~/.bash_profile
# by `flow setup`. Also emitted verbatim by `flow completion bash`.

_flow_slugs() {
    local f base
    for f in "$HOME"/.flow/state/*.json; do
        [ -e "$f" ] || continue
        base="${f##*/}"
        printf '%s\n' "${base%.json}"
    done
}

_flow_complete_dirs() {
    local cur="$1"
    if declare -F _filedir >/dev/null 2>&1; then
        _filedir -d
    else
        # `mapfile -t`, not `COMPREPLY=( $(compgen ...) )`: command-substitution
        # word-splits on whitespace, so paths like `~/My Projects/flow-src` would
        # split into two completion candidates. mapfile reads one path per line
        # verbatim, preserving spaces.
        mapfile -t COMPREPLY < <(compgen -d -- "$cur")
    fi
}

_flow() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    local verbs="setup new ls attach a done migrate completion version help --version -v --help -h"

    # Find the verb (first non-flag token after `flow`).
    local verb="" i
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) ;;
            *) verb="${words[i]}"; break ;;
        esac
    done

    # No verb yet — complete the verb list.
    if [ -z "$verb" ]; then
        # shellcheck disable=SC2207
        COMPREPLY=( $(compgen -W "$verbs" -- "$cur") )
        return
    fi

    case "$verb" in
        setup)
            case "$prev" in
                --source)
                    _flow_complete_dirs "$cur"
                    return
                    ;;
            esac
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "--upgrade --force --source --no-completions --no-hooks" -- "$cur") )
            ;;
        new)
            case "$prev" in
                --effort)
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "low medium high xhigh max" -- "$cur") )
                    return
                    ;;
            esac
            # When --resume appeared earlier in the line, every trailing
            # non-flag token is a slug (`flow new --resume x y z`). Complete
            # slugs cur-based (like `done`) so the SECOND+ slug completes too,
            # not just the first after `prev == --resume`.
            local has_resume="" j
            for ((j=1; j < cword; j++)); do
                if [ "${words[j]}" = "--resume" ]; then has_resume=1; break; fi
            done
            if [ -n "$has_resume" ] && [[ "$cur" != -* ]]; then
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
                return
            fi
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "--resume --no-auto-merge --effort --yes -y" -- "$cur") )
            ;;
        ls)
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "--cost --detail" -- "$cur") )
            ;;
        attach|a)
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
            ;;
        done)
            if [[ "$cur" == -* ]]; then
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "--merged --orphans --yes -y" -- "$cur") )
            else
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
            fi
            ;;
        migrate)
            case "$prev" in
                --scan)
                    _flow_complete_dirs "$cur"
                    return
                    ;;
            esac
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "--apply --include-orchestrator --scan" -- "$cur") )
            ;;
        completion)
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _flow flow
