#compdef flow
# zsh completion for `flow` — generated by hand, not codegen. Sourced by the
# `# managed by flow completions` block written into ~/.zshrc by `flow install`.
# Also emitted verbatim by `flow completion zsh`.

_flow_slugs() {
    local -a slugs
    slugs=(${(@f)$(print -l ${HOME}/.flow/state/*.json(N:t:r))})
    if (( ${#slugs} > 0 )); then
        _describe 'pipeline' slugs
    fi
}

_flow() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '1: :->verb' \
        '*:: :->args' \
        && return 0

    case $state in
        verb)
            local -a verbs
            verbs=(
                'install:install skills, agents, helpers globally'
                'feature:start or resume a pipeline'
                'epic:design or run an epic'
                'config:inspect flow configuration'
                'ls:list active pipelines'
                'attach:attach to a pipeline window'
                'a:alias for attach'
                'done:close a pipeline window'
                'completion:print a shell completion script'
                'version:print flow version'
                'help:show help'
                '--version:print flow version'
                '-v:print flow version'
                '--help:show help'
                '-h:show help'
            )
            _describe 'verb' verbs
            ;;
        args)
            case $line[1] in
                install)
                    _arguments \
                        '--upgrade[reap orphan symlinks]' \
                        '--force[overwrite real files at install targets]' \
                        '--source[override flow source root]:source dir:_files -/' \
                        '--no-completions[skip rc-file editing; remove existing block if present]' \
                        '--no-hooks[skip Stop-hook merge into ~/.claude/settings.json]' \
                        '--no-pull-canonical[skip pulling the canonical source before symlinking]' \
                        '--repair-settings[back up and rewrite ~/.claude/settings.json when malformed]' \
                        '--install-deps[install missing source-root runtime deps before symlinking]'
                    ;;
                feature)
                    # Second-level dispatch mirroring `epic`: after `create`,
                    # offer its create-level flags; after `resume`, complete a
                    # repeating slug list. Otherwise complete the subcommand
                    # list. ($line[1] is `feature`; $line[2] is the subcommand.)
                    if [[ "$line[2]" == create ]]; then
                        _arguments \
                            '--no-auto-merge[stop at gated regardless of rubric]' \
                            '--wait-for-copilot[force the full 10-min Copilot wait]' \
                            '--research[force web-grounded discovery research on, bypassing the relevance gate]' \
                            '--copilot-review[Copilot review opt-in]:mode:(auto always never)' \
                            '--effort[Claude Code reasoning effort]:level:(low medium high xhigh max)' \
                            '--model[whole-session Claude model alias]:alias:(opus haiku sonnet fable)' \
                            '--model-planning[model for the planning phase]:alias:(opus haiku sonnet fable)' \
                            '--model-implement[model for the implement phase]:alias:(opus haiku sonnet fable)' \
                            '--model-review[model for the review phase]:alias:(opus haiku sonnet fable)' \
                            '--model-verify[model for the verify phase (defaults to sonnet)]:alias:(opus haiku sonnet fable)' \
                            '--model-fix-applier[model for the fix-applier phase]:alias:(opus haiku sonnet fable)' \
                            '--model-consolidator[model for the consolidator phase]:alias:(opus haiku sonnet fable)' \
                            '--model-merge-resolver[model for the merge-resolver phase]:alias:(opus haiku sonnet fable)' \
                            '*::description:'
                    elif [[ "$line[2]" == resume ]]; then
                        _arguments \
                            '(--yes -y)'{--yes,-y}'[skip the multi-resume confirmation]' \
                            '*::pipeline:_flow_slugs'
                    else
                        local -a sub
                        sub=(
                            'create:start a new pipeline'
                            'resume:resume one or more crashed pipelines'
                        )
                        _describe 'subcommand' sub
                    fi
                    ;;
                epic)
                    # Second-level dispatch: after `create`, offer its
                    # create-level value flags; after `run`, advertise the run
                    # flags; otherwise complete the subcommand list. ($line[1]
                    # is the `epic` verb; $line[2] is the chosen subcommand.)
                    if [[ "$line[2]" == create ]]; then
                        _arguments \
                            '--resume[resume a crashed epic-design session]:pipeline:_flow_slugs' \
                            '--effort[Claude Code reasoning effort]:level:(low medium high xhigh max)' \
                            '--model[whole-session Claude model alias]:alias:(opus haiku sonnet fable)' \
                            '--model-planning[model for the design/planning phase]:alias:(opus haiku sonnet fable)' \
                            '*::prompt:'
                    elif [[ "$line[2]" == run ]]; then
                        _arguments \
                            '--model[whole-session model for the /flow-epic-run supervisor]:alias:(opus haiku sonnet fable)' \
                            '--effort[Claude Code reasoning effort for the /flow-epic-run supervisor]:level:(low medium high xhigh max)'
                    elif [[ "$line[2]" == status ]]; then
                        _arguments \
                            '--json[emit a machine-readable board (hypothesis to verify)]'
                    elif [[ "$line[2]" == bind ]]; then
                        _arguments \
                            '--external[record a completed out-of-band feature]:ref:' \
                            '--force[overwrite a differing binding / bypass the slug guard]'
                    elif [[ "$line[2]" == launch ]]; then
                        _arguments \
                            '--force[relaunch an already-bound feature]' \
                            '--model[per-launch model override, wins over flowNewHints]:alias:(opus haiku sonnet fable)' \
                            '--effort[per-launch effort override, wins over flowNewHints]:level:(low medium high xhigh max)'
                    else
                        local -a sub
                        sub=(
                            'create:design an epic'
                            'run:open the /flow-epic-run playbook window'
                            'status:render the live epic board (read-only)'
                            'bind:repoint or adopt a feature run.json binding'
                            'launch:atomically create + bind a feature'
                            'ls:list epics with per-state feature counts'
                        )
                        _describe 'subcommand' sub
                    fi
                    ;;
                config)
                    # Second-level dispatch mirroring `epic`: after `models`,
                    # offer its --slug/--json flags; otherwise complete the
                    # subcommand list. ($line[1] is `config`; $line[2] is the
                    # subcommand.)
                    if [[ "$line[2]" == models ]]; then
                        _arguments \
                            '--slug[overlay a pipeline'\''s per-run overrides]:pipeline:_flow_slugs' \
                            '--json[emit machine-readable JSON rows]'
                    else
                        local -a sub
                        sub=(
                            'models:show resolved model + effort per phase/agent'
                        )
                        _describe 'subcommand' sub
                    fi
                    ;;
                ls)
                    _arguments \
                        '--cost[add a $ column summed across the supervisor session]' \
                        '--detail[break cost down by model (requires --cost)]'
                    ;;
                attach|a)
                    _flow_slugs
                    ;;
                done)
                    _arguments \
                        '--merged[close every merged or cancelled window]' \
                        '--orphans[close every state file whose tmux window is gone]' \
                        '(--yes -y)'{--yes,-y}'[skip confirmation]' \
                        '*::pipeline:_flow_slugs'
                    ;;
                completion)
                    local -a shells
                    shells=('bash:bash completion script' 'zsh:zsh completion script')
                    _describe 'shell' shells
                    ;;
            esac
            ;;
    esac
}

compdef _flow flow
