#!/usr/bin/env bash
# bash completion for `flow` — generated by hand, not codegen. Sourced by the
# `# managed by flow completions` block written into ~/.bashrc / ~/.bash_profile
# by `flow install`. Also emitted verbatim by `flow completion bash`.

_flow_slugs() {
    local f base
    for f in "$HOME"/.flow/state/*.json; do
        [ -e "$f" ] || continue
        base="${f##*/}"
        printf '%s\n' "${base%.json}"
    done
}

_flow_complete_dirs() {
    local cur="$1"
    if declare -F _filedir >/dev/null 2>&1; then
        _filedir -d
    else
        # `mapfile -t`, not `COMPREPLY=( $(compgen ...) )`: command-substitution
        # word-splits on whitespace, so paths like `~/My Projects/flow-src` would
        # split into two completion candidates. mapfile reads one path per line
        # verbatim, preserving spaces.
        mapfile -t COMPREPLY < <(compgen -d -- "$cur")
    fi
}

_flow() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    local verbs="install feature epic config ls attach a done completion version help --version -v --help -h"

    # Find the verb (first non-flag token after `flow`).
    local verb="" i
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) ;;
            *) verb="${words[i]}"; break ;;
        esac
    done

    # No verb yet — complete the verb list.
    if [ -z "$verb" ]; then
        # shellcheck disable=SC2207
        COMPREPLY=( $(compgen -W "$verbs" -- "$cur") )
        return
    fi

    case "$verb" in
        install)
            case "$prev" in
                --source)
                    _flow_complete_dirs "$cur"
                    return
                    ;;
            esac
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "--upgrade --force --source --no-completions --no-hooks --no-pull-canonical --repair-settings --install-deps" -- "$cur") )
            ;;
        feature)
            # Find the feature subcommand (first non-flag token after `feature`).
            # `i` is the verb index from the scan above, so the subcommand starts
            # at i+1. Complete `create`'s flags / `resume`'s slug list; otherwise
            # the subcommand list. Mirrors the `epic)` arm below.
            local fsub="" k
            for ((k=i+1; k < cword; k++)); do
                case "${words[k]}" in
                    -*) ;;
                    *) fsub="${words[k]}"; break ;;
                esac
            done
            if [ "$fsub" = "create" ]; then
                case "$prev" in
                    --effort)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "low medium high xhigh max" -- "$cur") )
                        return
                        ;;
                    --model|--model-planning|--model-implement|--model-review|--model-verify|--model-fix-applier|--model-consolidator|--model-merge-resolver)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "opus haiku sonnet fable" -- "$cur") )
                        return
                        ;;
                    --copilot-review)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "auto always never" -- "$cur") )
                        return
                        ;;
                esac
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "--no-auto-merge --wait-for-copilot --research --copilot-review --effort --model --model-planning --model-implement --model-review --model-verify --model-fix-applier --model-consolidator --model-merge-resolver" -- "$cur") )
            elif [ "$fsub" = "resume" ]; then
                # Every trailing non-flag token is a slug (`flow feature resume
                # x y z`); complete slugs cur-based (like `done`) so the SECOND+
                # slug completes too. --yes/-y bypasses the multi-resume preview.
                if [[ "$cur" == -* ]]; then
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "--yes -y" -- "$cur") )
                else
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
                fi
            else
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "create resume" -- "$cur") )
            fi
            ;;
        epic)
            # Find the epic subcommand (first non-flag token after `epic`). `i`
            # is the verb index from the scan above, so the subcommand starts at
            # i+1. Complete each subcommand's value flags; otherwise the
            # subcommand list.
            local esub="" k
            for ((k=i+1; k < cword; k++)); do
                case "${words[k]}" in
                    -*) ;;
                    *) esub="${words[k]}"; break ;;
                esac
            done
            if [ "$esub" = "create" ]; then
                case "$prev" in
                    --resume)
                        # `flow epic create --resume <slug>` takes a slug, not a
                        # bare flag — complete it like `attach`/`feature`'s resume path.
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
                        return
                        ;;
                    --effort)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "low medium high xhigh max" -- "$cur") )
                        return
                        ;;
                    --model|--model-planning)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "opus haiku sonnet fable" -- "$cur") )
                        return
                        ;;
                esac
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "--resume --effort --model --model-planning" -- "$cur") )
            elif [ "$esub" = "run" ]; then
                case "$prev" in
                    --model)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "opus haiku sonnet fable" -- "$cur") )
                        return
                        ;;
                    --effort)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "low medium high xhigh max" -- "$cur") )
                        return
                        ;;
                esac
                if [[ "$cur" == -* ]]; then
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "--model --effort" -- "$cur") )
                fi
            elif [ "$esub" = "status" ]; then
                if [[ "$cur" == -* ]]; then
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "--json" -- "$cur") )
                fi
            elif [ "$esub" = "bind" ]; then
                if [[ "$cur" == -* ]]; then
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "--external --force" -- "$cur") )
                fi
            elif [ "$esub" = "launch" ]; then
                case "$prev" in
                    --model)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "opus haiku sonnet fable" -- "$cur") )
                        return
                        ;;
                    --effort)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "low medium high xhigh max" -- "$cur") )
                        return
                        ;;
                esac
                if [[ "$cur" == -* ]]; then
                    # shellcheck disable=SC2207
                    COMPREPLY=( $(compgen -W "--force --model --effort" -- "$cur") )
                fi
            else
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "create run status bind launch ls" -- "$cur") )
            fi
            ;;
        config)
            # Find the config subcommand (first non-flag token after `config`).
            # `i` is the verb index from the scan above, so the subcommand starts
            # at i+1. The only subcommand is `models`; complete its --slug/--json
            # flags. Mirrors the `epic)` arm.
            local csub="" k
            for ((k=i+1; k < cword; k++)); do
                case "${words[k]}" in
                    -*) ;;
                    *) csub="${words[k]}"; break ;;
                esac
            done
            if [ "$csub" = "models" ]; then
                case "$prev" in
                    --slug)
                        # shellcheck disable=SC2207
                        COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
                        return
                        ;;
                esac
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "--slug --json --help" -- "$cur") )
            else
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "models" -- "$cur") )
            fi
            ;;
        ls)
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "--cost --detail" -- "$cur") )
            ;;
        attach|a)
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
            ;;
        done)
            if [[ "$cur" == -* ]]; then
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "--merged --orphans --yes -y" -- "$cur") )
            else
                # shellcheck disable=SC2207
                COMPREPLY=( $(compgen -W "$(_flow_slugs)" -- "$cur") )
            fi
            ;;
        completion)
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _flow flow
