#compdef flow
# zsh completion for `flow` — generated by hand, not codegen. Sourced by the
# `# managed by flow completions` block written into ~/.zshrc by `flow setup`.
# Also emitted verbatim by `flow completion zsh`.

_flow_slugs() {
    local -a slugs
    slugs=(${(@f)$(print -l ${HOME}/.flow/state/*.json(N:t:r))})
    if (( ${#slugs} > 0 )); then
        _describe 'pipeline' slugs
    fi
}

_flow() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '1: :->verb' \
        '*:: :->args' \
        && return 0

    case $state in
        verb)
            local -a verbs
            verbs=(
                'setup:install skills, agents, helpers globally'
                'new:start a new pipeline'
                'epic:design or run an epic'
                'ls:list active pipelines'
                'attach:attach to a pipeline window'
                'a:alias for attach'
                'done:close a pipeline window'
                'migrate:clean up legacy per-repo install'
                'completion:print a shell completion script'
                'version:print flow version'
                'help:show help'
                '--version:print flow version'
                '-v:print flow version'
                '--help:show help'
                '-h:show help'
            )
            _describe 'verb' verbs
            ;;
        args)
            case $line[1] in
                setup)
                    _arguments \
                        '--upgrade[reap orphan symlinks]' \
                        '--force[overwrite real files at install targets]' \
                        '--source[override flow source root]:source dir:_files -/' \
                        '--no-completions[skip rc-file editing; remove existing block if present]' \
                        '--no-hooks[skip Stop-hook merge into ~/.claude/settings.json]'
                    ;;
                new)
                    # When --resume appears, the trailing positionals are a
                    # repeating slug list (`flow new --resume x y z`); complete
                    # each via _flow_slugs. Otherwise the rest is a free-text
                    # description (no completion). Mirrors `done`'s `*::` rest.
                    #
                    # `(i)` gives the FIRST-match index (or ${#words}+1 when
                    # absent), so --resume only counts when it precedes a POSIX
                    # `--` sentinel: `flow new -- fix --resume crash` treats the
                    # later `--resume` as free-text description, not the flag.
                    local resume_i=${words[(i)--resume]} dd_i=${words[(i)--]}
                    if (( resume_i <= ${#words} && resume_i < dd_i )); then
                        _arguments \
                            '--resume[resume one or more crashed pipelines]' \
                            '(--yes -y)'{--yes,-y}'[skip the multi-resume confirmation]' \
                            '*::pipeline:_flow_slugs'
                    else
                        _arguments \
                            '--resume[resume a crashed pipeline]' \
                            '--no-auto-merge[stop at gated regardless of rubric]' \
                            '--research[force web-grounded discovery research on, bypassing the relevance gate]' \
                            '--effort[Claude Code reasoning effort]:level:(low medium high xhigh max)' \
                            '--model[Claude Code model alias]:alias:(opus haiku sonnet fable)' \
                            '*::description:'
                    fi
                    ;;
                epic)
                    # Second-level dispatch: once `create` is the subcommand on
                    # the line ($line[2]), offer its create-level value flags;
                    # otherwise complete the subcommand list. ($line[1] is the
                    # `epic` verb itself.)
                    if [[ $line[2] == create ]]; then
                        _arguments \
                            '--resume[resume a crashed epic-design session]' \
                            '--effort[Claude Code reasoning effort]:level:(low medium high xhigh max)' \
                            '--model[Claude Code model alias]:alias:(opus haiku sonnet fable)' \
                            '*::prompt:'
                    else
                        local -a sub
                        sub=(
                            'create:design an epic'
                            'run:run an epic (deferred)'
                            'status:epic status (deferred)'
                            'ls:list epics (deferred)'
                        )
                        _describe 'subcommand' sub
                    fi
                    ;;
                ls)
                    _arguments \
                        '--cost[add a $ column summed across the supervisor session]' \
                        '--detail[break cost down by model (requires --cost)]'
                    ;;
                attach|a)
                    _flow_slugs
                    ;;
                done)
                    _arguments \
                        '--merged[close every merged or cancelled window]' \
                        '--orphans[close every state file whose tmux window is gone]' \
                        '(--yes -y)'{--yes,-y}'[skip confirmation]' \
                        '*::pipeline:_flow_slugs'
                    ;;
                migrate)
                    _arguments \
                        '--apply[actually perform the migration (default is dry-run)]' \
                        '--include-orchestrator[also delete .orchestrator/]' \
                        '--scan[dry-run across every git repo under a path]:scan dir:_files -/'
                    ;;
                completion)
                    local -a shells
                    shells=('bash:bash completion script' 'zsh:zsh completion script')
                    _describe 'shell' shells
                    ;;
            esac
            ;;
    esac
}

compdef _flow flow
